WIP: Speed up render
oncojs/oncogrid pull request #34
Opened 2017-06-15 21:12 UTC by Jephuff

This currently cuts initial render time by about 50%

2017-06-22 23:05 UTC, shanewilson commented
are you publishing to npm when you have those version commits?

2017-06-22 23:17 UTC, Jephuff commented
They are published with the beta tag.

2017-06-23 18:55 UTC, shanewilson commented
should be `1.4.0-beta.3` maybe then?

2017-06-23 19:08 UTC, Jephuff commented
I've never loved adding things to the version, but yeah in this case that probably would have been a good idea :)

2017-07-24 15:55 UTC, andricDu requested changes

2017-07-24 15:55 UTC, andricDu commented on API.md
> +* `setHeatmap()` - Set heatMap mode, accepts `true` or `false`.
might want to specify the argument type here.

2017-07-24 15:55 UTC, merged

2017-07-24 15:56 UTC, Jephuff commented on API.md
> +* `setHeatmap()` - Set heatMap mode, accepts `true` or `false`.
ahh oops, I'll make a pr to fix that :)